# Generated by Django 5.2 on 2025-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='password',
            field=models.CharField(default=12345, max_length=300),
            preserve_default=False,
        ),
    ]
