# Generated by Django 5.2 on 2025-08-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teachermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
